### ISSUE TITLE
<ERROR:PluginManager> Failed to enable plugin: MeaMailPlus

### ISSUE THREAD

**Issue by mxtilx** [Coooookies/Grasscutter-MeaMailPlus#14]
<ERROR:PluginManager> Failed to enable plugin: MeaMailPlus
java.lang.NullPointerException: Cannot invoke "io.github.gmw.module.TaskManager.enable()" because "this.task" is null
        at io.github.gmw.MeaMailPlusCore.onEnable(MeaMailPlusCore.java:42)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)

**Comment by jibanyouso** [comment]
一样
